"""empty message

Revision ID: 2660e96f3d3a
Revises: 
Create Date: 2023-02-28 02:07:08.637468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2660e96f3d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypters')
    op.drop_table('remotes')
    op.drop_table('exploits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploits',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('product_image', sa.TEXT(), nullable=True),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True)
    )
    op.create_table('remotes',
    sa.Column('id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('product_image', sa.TEXT(), nullable=True),
    sa.Column('product_description', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crypters',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('product_image', sa.TEXT(), nullable=True),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True)
    )
    # ### end Alembic commands ###
