"""empty message

Revision ID: 45302b603916
Revises: 29294584932e
Create Date: 2023-02-28 02:48:07.735583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45302b603916'
down_revision = '29294584932e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_crypters')
    with op.batch_alter_table('crypters', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypters', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('_alembic_tmp_crypters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('product_image', sa.VARCHAR(length=50000), nullable=True),
    sa.Column('product_description', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
