"""empty message

Revision ID: 52eb5dfacd72
Revises: 9edf4589f003
Create Date: 2023-02-28 02:28:49.563439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52eb5dfacd72'
down_revision = '9edf4589f003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypters', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypters', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
