"""empty message

Revision ID: 9edf4589f003
Revises: 2660e96f3d3a
Create Date: 2023-02-28 02:13:48.002051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edf4589f003'
down_revision = '2660e96f3d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_image', sa.String(length=50000), nullable=True),
    sa.Column('product_description', sa.String(length=10000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exploits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_image', sa.String(length=50000), nullable=True),
    sa.Column('product_description', sa.String(length=10000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_image', sa.String(length=50000), nullable=True),
    sa.Column('product_description', sa.String(length=10000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remotes')
    op.drop_table('exploits')
    op.drop_table('crypters')
    # ### end Alembic commands ###
